# 配置数据源信息
spring:
  datasource:                                   # 数据源的相关配置
    url: jdbc:mysql://localhost:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=GMT%2B8
    password: root
  redis:
    # Redis 单机单实例
    database: 1
    host: localhost
    port: 6379
    password: xwcoding
    # Redis 哨兵模式
#    database: 1
#    password: xwcoding
#    sentinel:
#      master: xw-master
#      nodes: 192.168.1.191:26379,192.168.1.192:26379,192.168.1.193:26379
    # Redis 集群模式
#    password: xwcoding
#    cluster:
#      nodes: 192.168.1.201:6379,192.168.1.202:6379,192.168.1.203:6379,192.168.1.204:6379,192.168.1.205:6379,192.168.1.206:6379

# mybatis 配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 仅限于开发环境或者测试环境使用