server:
  port: 8091

spring:
  datasource:                                   # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource    # 数据源类型：HikariCP
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql驱动
    url: jdbc:mysql://localhost:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=GMT%2B8
    username: root
    password: root
  redis:
    # Redis 单机单实例
    database: 1
    host: localhost
    port: 6379
    password: xwcoding
  data:
    elasticsearch:
      cluster-name: les
      cluster-nodes: 192.168.31.197:9300
