# 内置tomcat
# web访问端口号  约定：8088
server:
  port: 8066
  tomcat:
    uri-encoding: UTF-8
  jetty:
    max-http-post-size: 80KB

# 配置数据源信息
spring:
  datasource:                                   # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource    # 数据源类型：HikariCP
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql驱动
#    url: jdbc:mysql://localhost:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=GMT%2B8
    username: root
#    password: root
    hikari:
      connection-timeout: 30000       # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException，默认：30秒
      minimum-idle: 5                 # 最小连接数 HikariCP 没有设置，最小保持和最大一致   最小连接数设置为5～10，在DEV和TEST环境设置为5，上线之后设置为10，
      maximum-pool-size: 20           # 最大连接数 HikariCP 默认10                     日常开发中多数项目最大连接数设置为20， 最大连接数还是和服务器的硬件有关，并非越大越好
      auto-commit: true               # 自动提交
      idle-timeout: 600000            # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DateSourceHikariCP   # 连接池名字
      max-lifetime: 1800000           # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms
      connection-test-query: SELECT 1
  servlet:
    multipart:
      max-file-size: 512000 # 文件上传大小限制为500kb
      max-request-size: 512000  # 请求大小限制为500kb
  session:
    store-type: redis
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html

  profiles:
    active: dev

# mybatis 配置
mybatis:
  type-aliases-package: com.xw.pojo   # 所有POJO类所在包路径
  mapper-locations: classpath:mapper/*.xml      # mapper映射文件
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 仅限于开发环境或者测试环境使用

# mybatis mapper 配置
# 通用 mapper 配置
mapper:
  mappers: com.xw.my.mapper.MyMapper
  not-empty: false  # 在进行数据库操作的时候，判断表达式 username != null，是否追加 username != ''
  identity: MYSQL   # 数据库方言

# 分页插件配置
pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true

# FastDFS 配置
fdfs:
  connect-timeout: 30 # 连接超时时间
  so-timeout: 30      # 读取时间
  tracker-list: 192.168.229.11:22122  # tracker 服务配置地址列表（ip:端口号）